name: CI/CD Pipeline for Bob's App

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  # PREMIER JOB : Test, Analyse et Build
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: front/package-lock.json

      # --- Séquence Backend ---
      - name: Run Backend Tests & Build
        run: mvn -B verify
        working-directory: ./back

      # --- Séquence Frontend ---
      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./front
      - name: Run Frontend Tests
        run: npm test -- --code-coverage --watch=false --browsers=ChromeHeadless
        working-directory: ./front
      - name: Build Frontend Application
        run: npm run build -- --configuration production
        working-directory: ./front
      
      # --- Séquence Analyse ---
      - name: Generate dependency classpath for Sonar
        run: mvn dependency:build-classpath -Dmdep.outputFile=.sonar/classpath.txt
        working-directory: ./back
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      # --- Uploader les artefacts pour le job suivant ---
      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: back/target/*.jar

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: front/dist/

  # DEUXIÈME JOB : Publication des images Docker
  build-and-push-images:
    needs: test-and-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Télécharger les artefacts du job précédent ---
      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: back/target/
      
      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: front/dist/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- AMÉLIORATION : Ajout d'un tag unique ---
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-backend:${{ github.sha }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-frontend:${{ github.sha }}
