name: CI Pipeline for Bob's App

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # On doit récupérer l'historique complet pour que Sonar puisse analyser la PR correctement
        with:
          fetch-depth: 0

      - name: Set up JDK 11 with Temurin distribution
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: front/package-lock.json

      - name: Run Backend Tests with Maven
        run: mvn -B verify # On utilise 'verify' au lieu de 'test' pour s'assurer que tout est bien packagé avant l'analyse
        working-directory: ./back

      - name: Upload backend coverage report (JaCoCo)
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: back/target/site/jacoco/

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./front
      
      - name: Run Frontend Tests and generate coverage
        run: npm test -- --code-coverage --watch=false --browsers=ChromeHeadless
        working-directory: ./front

      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: front/coverage/

      # Étape finale et nouvelle
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
